// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Infrastructure.Persistence;

#nullable disable

namespace Product.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207064146_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 12, 7, 6, 41, 45, 131, DateTimeKind.Utc).AddTicks(9318),
                            Description = "Ergonomic wireless mouse with 6 buttons",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            SKU = "WM-001",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 12, 7, 6, 41, 45, 131, DateTimeKind.Utc).AddTicks(9326),
                            Description = "RGB mechanical keyboard with Cherry MX switches",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            SKU = "KB-002",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 12, 7, 6, 41, 45, 131, DateTimeKind.Utc).AddTicks(9329),
                            Description = "7-in-1 USB-C hub with HDMI and card reader",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "USB-C Hub",
                            Price = 45.99m,
                            SKU = "HUB-003",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 12, 7, 6, 41, 45, 131, DateTimeKind.Utc).AddTicks(9332),
                            Description = "Adjustable aluminum laptop stand",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Laptop Stand",
                            Price = 39.99m,
                            SKU = "LS-004",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 12, 7, 6, 41, 45, 131, DateTimeKind.Utc).AddTicks(9341),
                            Description = "1080p HD webcam with built-in microphone",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Webcam HD",
                            Price = 69.99m,
                            SKU = "WC-005",
                            StockQuantity = 90
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
